# Generated by Django 4.2.4 on 2023-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comidas',
            field=models.ManyToManyField(to='core.comida'),
        ),
    ]
